language: haxe
sudo: false
dist: trusty
haxe:
 - development

install:
 - haxelib git vshaxe-build https://github.com/vshaxe/vshaxe-build

script:
 - haxelib run vshaxe-build -v --debug -t all -m both
 - haxelib run vshaxe-build -v -t vshaxe